import React from "react";
import { Metadata } from "next";
import sampleData from "@/db/sample-data";
import ProductList from "@/components/shared/products/product-list";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

function HomePage() {
  return (
    <div>
      <ProductList data={sampleData.products} title="New Products" limit={4} />
    </div>
  );
}

export default HomePage;
