import { Button } from "@/components/ui/button";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

function HomePage() {
  return (
    <div>
      <h3 className="h3-bold">HomePage</h3>
      <Button size="lg">Click Me</Button>
    </div>
  );
}

export default HomePage;
