import React from "react";
import { Metadata } from "next";
import ProductList from "@/components/shared/products/product-list";
import { getLatestProducts } from "@/lib/actions/product.actions";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const HomePage = async () => {
  const latestproducts = await getLatestProducts();
  return (
    <div>
      <ProductList data={latestproducts} title="New Products" />
    </div>
  );
};

export default HomePage;
